inputSet:
  identifier: "default"
  pipeline:
    identifier: "harness_as_code"
    stages:
    - stage:
        identifier: "apply"
        type: "Custom"
        spec:
          execution:
            steps:
            - step:
                identifier: "assume"
                template:
                  templateInputs:
                    type: "ShellScript"
                    spec:
                      environmentVariables:
                      - name: "TARGET_ROLE_ARN"
                        type: "String"
                        value: "arn:aws:iam::759984737373:role/rileysnyderharnessio-assumed"
  name: "default"
  orgIdentifier: "default"
  projectIdentifier: "Default_Project_1662659562703"
